car/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.CarBrandListView.as_view(),
        name='car_brand_list'
        ),
    url(
        r'^(?P<slug>[\w\d-]+)/$',
        views.CarBrandDetailView.as_view(),
        name='car_brand_detail'
    ),
    url(
        r'^(?P<brand_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$',
        views.CarModelDetailView.as_view(),
        name='car_model_detail'
    ),
    url(
        r'^(?P<brand_slug>[\w\d-]+)/(?P<model_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$',
        views.CarSubModelDetailView.as_view(),
        name='car_sub_model_detail'
    ),
]

driftsetups/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from home.views import SitemapXmlView

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^c/', include('car.urls')),
    url(r'^s/', include('setup.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^', include('home.urls')),
    url(r'^api/v1/', include('rest_api.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^sitemap\.xml/$', SitemapXmlView.as_view()),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False,
)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy'),
    url(r'^tos/$', views.TOSView.as_view(), name='tos'),
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    city = models.CharField(max_length=200, default=None, null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_avatar(self):
        try:
            return self.avatar.url
        except ValueError:
            return 'https://driftsetups.s3.amazonaws.com/media/no-avatar.png'

    def get_absolute_url(self):
        return reverse('user', args=[str(self.id)])

    def __str__(self):
        return self.get_full_name()

car/models.py
from autoslug import AutoSlugField
from itertools import chain

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse

from setup.models import Setup


class Engine(models.Model):
    name = models.CharField(max_length=100)
    producer = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class CarImage(models.Model):
    image = models.ImageField(upload_to='cars/', blank=True, default=None, null=True)
    is_main = models.BooleanField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    car = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.image.url


class CarBrand(models.Model):
    name = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='name', unique=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def get_setups(self):
        setups = chain()
        car_models = CarModel.objects.filter(brand=self)
        car_model_sub_models = chain()
        for car_model in car_models:
            setups = chain(
                setups,
                car_model.setups.all()
            )
            car_model_sub_models = chain(
                car_model_sub_models,
                car_model.get_sub_models(),
            )
        for car_sub_model in car_model_sub_models:
            setups = chain(
                setups,
                car_sub_model.setups.all(),
            )
        return setups

    def get_absolute_url(self):
        return reverse('car_brand_detail', args=[str(self.slug)])

    def __str__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=100)
    brand = models.ForeignKey(CarBrand)
    stock_engines = models.ManyToManyField(Engine, blank=True)
    setups = GenericRelation(Setup, related_query_name='car_model_setup')
    views = models.PositiveIntegerField(default=0)
    slug = AutoSlugField(populate_from='name', unique=True)
    images = GenericRelation(CarImage, related_query_name='car_model_images')
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def increase_views(self):
        self.views += 1
        self.save()

    def get_main_image(self):
        return self.images.get(is_main=True)

    def get_car_brand(self):
        return self.brand

    def get_car_model(self):
        return self

    def get_sub_models(self):
        return CarSubModel.objects.filter(car_model=self)

    def split_tags(self):
        car_name = '{0} {1}'.format(self.brand, self.name)
        return car_name.split(' ')

    def get_setups(self):
        setups = chain()
        for car_sub_model in self.get_sub_models():
            setups = chain(
                setups,
                car_sub_model.setups.all(),
            )
        return setups

    def get_absolute_url(self):
        return reverse('car_model_detail', args=[str(self.brand.slug), str(self.slug)])

    def __str__(self):
        return '{0} {1}'.format(self.brand, self.name)


class CarSubModel(models.Model):
    name = models.CharField(max_length=100)
    car_model = models.ForeignKey(CarModel)
    stock_engines = models.ManyToManyField(Engine, blank=True)
    setups = GenericRelation(Setup, related_query_name='sub_model_setup')
    views = models.PositiveIntegerField(default=0)
    slug = AutoSlugField(populate_from='name', unique=True)
    images = GenericRelation(CarImage, related_query_name='sub_model_images')
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def get_car_brand(self):
        return self.car_model.brand

    def get_car_model(self):
        return self.car_model

    def increase_views(self):
        self.views += 1
        self.save()

    def split_tags(self):
        car_name = '{0} {1}'.format(self.car_model, self.name)
        return car_name.split(' ')

    def get_main_image(self):
        return self.images.get(is_main=True)

    def get_absolute_url(self):
        return reverse('car_sub_model_detail', args=[str(self.car_model.brand.slug), str(self.car_model.slug), str(self.slug)])

    def __str__(self):
        return '{0} {1}'.format(self.car_model, self.name)

setup/models.py
from autoslug import AutoSlugField
from datetime import datetime

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.shortcuts import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import ugettext_lazy as _

from accounts.models import User


class Setup(models.Model):
    name = models.CharField(max_length=200)
    engine = models.ForeignKey('car.Engine')
    power = models.IntegerField(default=None, blank=True, null=True)
    torque = models.IntegerField(default=None, blank=True, null=True)
    rev_limit = models.IntegerField(default=None, blank=True, null=True)
    weight = models.IntegerField(default=None, blank=True, null=True)
    weight_distribution = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=None, blank=True, null=True)
    boost = models.FloatField(default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)
    creator = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    car = GenericForeignKey('content_type', 'object_id')
    car_year = models.IntegerField(default=None, null=True, blank=True, verbose_name=_('Car Year'))
    views = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='name', unique=True)

    def get_main_image(self):
        try:
            return SetupImage.objects.filter(setup=self)[0]
        except IndexError:
            return None

    def get_additional_images(self):
        try:
            return SetupImage.objects.filter(setup=self)[1:]
        except IndexError:
            pass

    def get_all_images(self):
        return SetupImage.objects.filter(setup=self)

    def get_engine_fields(self):
        return SetupField.objects.filter(setup=self, category=0)

    def get_drivetrain_fields(self):
        return SetupField.objects.filter(setup=self, category=1)

    def get_suspension_fields(self):
        return SetupField.objects.filter(setup=self, category=2)

    def get_brakes_fields(self):
        return SetupField.objects.filter(setup=self, category=3)

    def get_wheels_fields(self):
        return SetupField.objects.filter(setup=self, category=4)

    def get_exterior_fields(self):
        return SetupField.objects.filter(setup=self, category=5)

    def get_interior_fields(self):
        return SetupField.objects.filter(setup=self, category=6)

    def get_votes_total(self):
        return SetupVote.objects.filter(setup=self).count()

    def get_up_votes_total(self):
        return SetupVote.objects.filter(setup=self, vote=1).count()

    def get_votes_percentage(self):
        votes_total = self.get_votes_total()
        votes_up = self.get_up_votes_total()
        if votes_total != 0 and votes_up != 0:
            percentage = votes_up / votes_total * 100
            return int(percentage)
        else:
            return 0

    def get_full_name(self):
        return self.car.name()

    def increase_views(self):
        self.views += 1
        self.save()

    def get_absolute_url(self):
        return reverse('setup_detail', args=[self.slug])

    def __str__(self):
        return self.name


class SetupImage(models.Model):
    image = models.ImageField(upload_to='setups/', blank=True, default=None, null=True)
    order = models.IntegerField(default=0)
    setup = models.ForeignKey(Setup)

    class Meta:
        ordering = ['order']

    def __str__(self):
        try:
            return self.image.url
        except ValueError:
            return 'https://driftsetups.s3.amazonaws.com/media/no-photos-thumbnail.png'


class SetupField(models.Model):
    CATEGORIES = (
        (0, _('Engine')),
        (1, _('Drivetrain')),
        (2, _('Steering/Suspension')),
        (3, _('Brakes')),
        (4, _('Wheels')),
        (5, _('Exterior')),
        (6, _('Interior')),

    )
    field = models.CharField(max_length=300)
    setup = models.ForeignKey(Setup)
    category = models.SmallIntegerField(choices=CATEGORIES)

    def __str__(self):
        return self.field


class SetupVote(models.Model):
    VOTES = (
        (0, _('Vote Down')),
        (1, _('Vote Up')),
    )
    vote = models.BooleanField(default=0, choices=VOTES)
    setup = models.ForeignKey(Setup)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.vote

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

home/views.py
from itertools import chain

from django.views.generic import TemplateView
from django.utils import timezone

from car.models import CarBrand, CarModel, CarSubModel
from setup.models import Setup, SetupImage
from accounts.models import User


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['top_cars'] = sorted(
            list(
                chain(
                    CarSubModel.objects.all(),
                    CarModel.objects.all()
                )
            ), key=lambda instance: instance.views, reverse=True
        )[:4]
        context['top_setups_by_views'] = Setup.objects.order_by('-views')[:4]
        setups_by_votes = sorted(
            Setup.objects.all(),
            key=lambda s: s.get_votes_total(),
            reverse=True
        )[:100]
        context['top_setups_by_votes_percentage'] = sorted(
            setups_by_votes,
            key=lambda s: s.get_votes_percentage(),
            reverse=True
        )[:4]
        context['top_new_weekly_setups'] = Setup.objects.filter(
            timestamp__gte=timezone.now() - timezone.timedelta(days=7)
        ).order_by('-views')[:4]
        return context


class SitemapXmlView(TemplateView):
    template_name = 'sitemap.xml'
    content_type = 'text/xml'

    def get_context_data(self, **kwargs):
        context = super(SitemapXmlView, self).get_context_data(**kwargs)
        context['car_brands'] = CarBrand.objects.all()
        context['car_models'] = CarModel.objects.all()
        context['car_sub_models'] = CarSubModel.objects.all()
        context['setups'] = Setup.objects.all()
        context['profiles'] = User.objects.all()
        return context


class PrivacyView(TemplateView):
    template_name = 'privacy_policy.html'


class TOSView(TemplateView):
    template_name = 'terms_of_use.html'

templates/base.html
{% load i18n %}
{% load static %}
{% load car_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | DRIFTSETUPS</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <link rel="shortcut icon" type="image/ico" href="https://driftsetups.s3.amazonaws.com/favicon.ico" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Oswald:400,600,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" integrity="sha384-VY3F8aCQDLImi4L+tPX4XjtiJwXDwwyXNbkH7SHts0Jlo85t1R15MlXVBKLNx+dj" crossorigin="anonymous">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113163756-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-113163756-1');
    </script>

    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '2260072790885675');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=2260072790885675&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->


    {% block head %}{% endblock %}
</head>
<body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1974055282834324',
          xfbml      : true,
          version    : 'v2.12'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <header>
        <!--<div class="patreon">-->
            <!--<div class="patreon-container"><div class="patreon-text"><span>Enjoyed DriftSetups idea? You can support its development!</span><a target="_blank" href="https://www.patreon.com/bePatron?c=1510299">Become our Patreon!</a></div>-->
                <!--<div class="patreon-close">&times;</div>-->
            <!--</div>-->
        <!--</div>-->
        <nav>
            <div class="nav-left">
                <li>
                    <a href="{% url 'home' %}">
                        <div class="logo">DriftSetups</div>
                    </a>
                </li>
                <li class="menu-icon">☰</li>
                <li class="search-container">
                    <form id="searchform" action="{% url 'search_list' %}" method="get" accept-charset="utf-8">
                        <input type="text" placeholder="{% trans 'Search...' %}" name="q">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </li>
            </div>
            <div class="nav-right">
                <div class="menu-close">×</div>
                <li class="setup-create"><a href="{% url 'setup_create' %}" onclick="ga('send', 'event', 'Setup_Create', 'Click')">{% trans 'Create Setup' %}</a></li>
                <li><a href="{% url 'setup_list' %}">{% trans 'Top Setups' %}</a></li>
                <li><a href="{% url 'car_brand_list' %}">{% trans 'Cars' %}</a></li>
                <li class="in_dev">{% trans 'Engines' %}</li>
                <li><a target="_blank" href="{% trans 'https://www.liqpay.ua/en/checkout/card/driftsetups' %}" onclick="ga('send', 'event', 'Support_Us', 'Click')"><span class="heart">♥</span> {% trans 'Support us' %}</a></li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <div class="dropbtn">
                        <a href="{{ user.get_absolute_url }}"><img class="small-avatar" src="{{ user.get_avatar }}" height="50px" width="50px" alt="{{ user.first_name }}"></a>
                    </div>
                    <div class="dropdown-content">
                        <a href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                    </div>
                </li>
                {% else %}
                <li id="sign-up">{% trans 'Sign up' %}</li>
                <li id="login">{% trans 'Login' %}</li>
                {% endif %}
            </div>
        </nav>
    </header>
    {% block body %}{% endblock %}

<footer>
    {% block footer %}{% endblock %}
    <div class="bottom-top-cars">
        <h3>{% trans 'Drift Setups Car List' %}</h3>
        {% top_drift_cars %}
    </div>
    <div class="copyright">© <span id="_publisher" itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
        <span itemprop="name">DriftSetups.com</span>
        <span hidden itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
            <img itemprop="url" src="https://driftsetups.s3.amazonaws.com/driftsetups_logo_600_60.png"/>
                <meta itemprop="width" content="600">
                <meta itemprop="height" content="60">
        </span>
    </div>
    <div class="footer-social-buttons">
        <a href="https://www.instagram.com/driftsetups/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/DriftSetupscom-139539263386934/"><i class="fab fa-facebook-square"></i></a>
        <a href="https://twitter.com/driftsetups"><i class="fab fa-twitter-square"></i></a>
    </div>
    <div class="footer-privacy">
        <a href="{% url 'privacy' %}">{% trans 'Privacy Policy' %}</a>
        <a href="{% url 'tos' %}">{% trans 'Terms of Service' %}</a>
    </div>
</footer>
    <!-- Popups -->
    <div class="popup-background"></div>
    <div class="loader"></div>
    {% url 'login' as login_url %}
    {% if not user.is_authenticated and request.path != login_url %}
        <div class="popup-login-content">
            <span class="popup-close">&times;</span>
            <a href="{% url 'social:begin' 'google-oauth2' %}"><div class="google-signup center"><div class="google-signup-icon"></div><div class="google-signup-text">{% trans 'Log in with Google+' %}</div></div></a>
            <a href="{% url 'social:begin' 'facebook' %}"><div class="facebook-signup center"><div class="facebook-signup-icon"></div><div class="facebook-signup-text">{% trans 'Log in with Facebook' %}</div></div></a>
            <div class="center">{% trans 'or' %}</div>
            <div class="login-form">
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <input class="center" type="email" name="username" id="id_username" maxlength="254" required autofocus placeholder="{% trans 'Email address' %}">
                    <input class="center" type="password" name="password" id="id_password" required placeholder="{% trans 'Password' %}">
                    <button class="center" type="submit">{% trans 'Log in' %}</button>
                </form>
            </div>
        </div>

        <div class="popup-sign-up-content">
            <span class="popup-close">&times;</span>
            <div class="popup-sign-up-choice">
                <a href='{% url "social:begin" "google-oauth2" %}'><div class="google-signup center"><div class="google-signup-icon"></div><div class="google-signup-text">{% trans 'Sign up with Google+' %}</div></div></a>
                <a href='{% url "social:begin" "facebook" %}'><div class="facebook-signup center"><div class="facebook-signup-icon"></div><div class="facebook-signup-text">{% trans 'Sign up with Facebook' %}</div></div></a>
                <div class="center">{% trans 'or' %}</div>
                <div class="sign-up-with-email center">Email</div>
            </div>

            <div class="sign-up-with-email-form">
                <div class="center">{% trans 'Sign up with' %} <a href='{% url "social:begin" "facebook" %}'>Facebook</a>, <a href='{% url "social:begin" "google-oauth2" %}'>Google+</a></div>
                <div class="center">{% trans 'or' %}</div>
                <form action="{% url 'sign_up' %}" method="post">
                    {% csrf_token %}
                    <input class="center" type="email" name="email" autofocus id="id_email" required placeholder="{% trans 'Email address' %}">
                    <input class="center" type="text" name="first_name" id="id_first_name" maxlength="30" placeholder="{% trans 'First name' %}">
                    <input class="center" type="text" name="last_name" id="id_last_name" maxlength="30" placeholder="{% trans 'Last name' %}">
                    <input class="center" type="password" name="password1" required="" id="id_password1" placeholder="{% trans 'Password' %}">
                    <input class="center" type="password" name="password2" required="" id="id_password2" placeholder="{% trans 'Repeat password' %}">
                    <button class="center" type="submit">{% trans 'Sign up' %}</button>
                </form>
            </div>
        </div>
    {% endif %}
    <!-- Popups end -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

templates/car_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {% if car %}
        {{ car }} {% trans 'Drift Chassis' %}
    {% else %}
        {% trans 'Drift Cars Chassis By Brand' %}
    {% endif %}
{% endblock %}
{% block body %}
<div class="post-header-container">
    {% if car %}
    <h1>{{ car }} {% trans 'Drift Chassis' %}</h1>
    {% else %}
    <h1>{% trans 'Drift Car Chassis By Brand' %}</h1>
    {% endif %}
    <div class="car-list">
        <ul>
            {% for car_list_item in car_list %}
                {% if car_list_item.brand %}
                    <li><a href="{% url 'car_model_detail' car.slug car_list_item.slug %}">{{ car_list_item }}</a></li>
                {% elif car_list_item.car_model %}
                    <li><a href="{% url 'car_sub_model_detail' car.brand.slug car.slug car_list_item.slug %}">{{ car_list_item }}</a></li>
                {% else %}
                    <li><a href="{% url 'car_brand_detail' car_list_item.slug %}">{{ car_list_item }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    <div class="car-setups">
        <div class="setup-list-container">
        {% if setups %}
        <ul class="setup-list">
            {% for setup in setups %}
                <li class="setup-list-item">
                    <div class="setup-list-item-image-container">
                        <a href="{% url 'setup_detail' setup.slug %}">
                            {% if setup.get_main_image %}
                                <img width="300px" src="{{ setup.get_main_image }}" alt="{{ setup }}">
                            {% else %}
                                <img width="300px" src="https://driftsetups.s3.amazonaws.com/media/no-photos-thumbnail.png" alt="{{ setup }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="setup-list-item-heading-container">
                        <a href="{% url 'setup_detail' setup.slug %}">
                            <h2>{{ setup }}</h2>
                        </a>
                        <div>
                            <a class='href-underline' href="{{ setup.car.get_absolute_url }}">{{ setup.car}}</a>
                            {% trans 'by' %} <a class='href-underline' href="{% url 'user' setup.creator.id %}">{{ setup.creator }}</a> {% trans 'updated' %} {{ setup.timestamp|date:"F Y" }}
                        </div>
                        <div class="setup-characteristics-section">
                            <div class="round">
                                {% if setup.power %}
                                <div class="power">{{ setup.power }}hp</div>
                                {% else %}
                                <div class="power">----hp</div>
                                {% endif %}
                                <div class="char-title">{% trans 'Power' %}</div>
                            </div>
                            <div class="round">
                                {% if setup.torque %}
                                <div class="torque">{{ setup.torque }}Nm</div>
                                {% else %}
                                <div class="torque">----Nm</div>
                                {% endif %}
                                <div class="char-title">{% trans 'Torque' %}</div>
                            </div>
                            <div class="round">
                                {% if setup.rev_limit %}
                                <div class="rev-limit">{{ setup.rev_limit }}rpm</div>
                                {% else %}
                                <div class="rev-limit">----rpm</div>
                                {% endif %}
                                <div class="char-title">{% trans 'Rev Limit' %}</div>
                            </div>
                            <div class="round">
                               {% if setup.weight %}
                                <div class="weight">{{ setup.weight }}kg</div>
                                {% else %}
                                <div class="weight">----kg</div>
                                {% endif %}
                                <div class="char-title">{% trans 'Weight' %}</div>
                            </div>
                        </div>
                    </div>
                    <div class="setup-list-item-votes-container">
                        <div class="setup-info-total"><span>{% trans 'votes' %}:</span> {{ setup.get_votes_total }}</div>
                        <div class="votes-bar">
                            <div class="votes-bar-total" style="width:{{ setup.get_votes_percentage }}%"></div>
                        </div>
                        <div class="setup-info-total"><span>{% trans 'views' %}:</span> {{ setup.views }}</div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            {% url 'car_brand_list' as car_brand_list_home_url %}
            {% if request.path != car_brand_list_home_url %}
                <h2 class="no-setups">{% trans 'No setups? You own such car? Be first!' %} <a href="{% url 'setup_create' %}">{% trans 'Create one!!!' %}</a></h2>
            {% endif %}
        {% endif %}
    </div>
    </div>
</div>
{% endblock %}

templates/top_drift_cars.html
<ul>
    {% for car in top_drift_cars %}
        {% if car.car_model %}
            <li><a href="{% url 'car_sub_model_detail' car.car_model.brand.slug car.car_model.slug car.slug %}">{{ car }}</a></li>
        {% else %}
            <li><a href="{% url 'car_model_detail' car.brand.slug car.slug %}">{{ car }}</a></li>
        {% endif %}
    {% endfor %}
</ul>